version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: db-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
            MYSQL_USER: usr
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always

    web:
        image: app-name:latest
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
#        entrypoint: ["./wait-for-it.sh", "db", "--", "php-fpm"]

volumes:
    mysql_data:
